-- Account-level member lifecycle.
--
-- is_active is a login kill switch that deliberately leaves role_grants intact.
-- Deactivating by deleting grants would make the row vanish from every members
-- list while the account kept holding its slot in users_email_lower_key, with
-- no UI path back. Keeping the grants keeps the member visible, badged, and
-- reversible.
--
-- must_change_password marks an account whose password was generated by an
-- admin rather than chosen by its owner. The API refuses every request from
-- such an account except the password change itself, so a temp credential can
-- do nothing but replace itself.
ALTER TABLE users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE users ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT false;
