// GENERATED by gen_probes.py - do not hand-edit; line numbers are load-bearing.
// Each throw embeds its own source line so ground truth cannot silently drift.
// filler 0003 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0004 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0005 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0006 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0007 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0008 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0009 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0010 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0011 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0012 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0013 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0014 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0015 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0016 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0017 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0018 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0019 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0020 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0021 - padding so probe throws land on exact, pre-recorded line numbers
@pragma('vm:never-inline')
void probeA() {
  throw StateError('SAURON_PROBE id=A line=24');
}
// filler 0026 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0027 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0028 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0029 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0030 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0031 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0032 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0033 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0034 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0035 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0036 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0037 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0038 - padding so probe throws land on exact, pre-recorded line numbers
@pragma('vm:never-inline')
void probeB() {
  throw StateError('SAURON_PROBE id=B line=41');
}
// filler 0043 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0044 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0045 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0046 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0047 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0048 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0049 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0050 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0051 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0052 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0053 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0054 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0055 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0056 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0057 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0058 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0059 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0060 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0061 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0062 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0063 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0064 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0065 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0066 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0067 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0068 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0069 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0070 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0071 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0072 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0073 - padding so probe throws land on exact, pre-recorded line numbers
@pragma('vm:never-inline')
void probeC() {
  throw StateError('SAURON_PROBE id=C line=76');
}
// filler 0078 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0079 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0080 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0081 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0082 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0083 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0084 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0085 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0086 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0087 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0088 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0089 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0090 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0091 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0092 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0093 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0094 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0095 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0096 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0097 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0098 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0099 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0100 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0101 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0102 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0103 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0104 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0105 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0106 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0107 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0108 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0109 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0110 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0111 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0112 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0113 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0114 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0115 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0116 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0117 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0118 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0119 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0120 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0121 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0122 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0123 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0124 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0125 - padding so probe throws land on exact, pre-recorded line numbers
@pragma('vm:never-inline')
void probeD() {
  throw StateError('SAURON_PROBE id=D line=128');
}
// filler 0130 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0131 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0132 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0133 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0134 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0135 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0136 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0137 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0138 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0139 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0140 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0141 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0142 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0143 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0144 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0145 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0146 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0147 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0148 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0149 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0150 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0151 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0152 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0153 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0154 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0155 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0156 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0157 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0158 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0159 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0160 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0161 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0162 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0163 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0164 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0165 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0166 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0167 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0168 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0169 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0170 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0171 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0172 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0173 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0174 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0175 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0176 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0177 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0178 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0179 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0180 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0181 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0182 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0183 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0184 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0185 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0186 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0187 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0188 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0189 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0190 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0191 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0192 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0193 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0194 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0195 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0196 - padding so probe throws land on exact, pre-recorded line numbers
@pragma('vm:never-inline')
void probeE() {
  throw StateError('SAURON_PROBE id=E line=199');
}
// filler 0201 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0202 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0203 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0204 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0205 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0206 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0207 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0208 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0209 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0210 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0211 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0212 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0213 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0214 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0215 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0216 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0217 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0218 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0219 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0220 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0221 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0222 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0223 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0224 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0225 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0226 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0227 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0228 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0229 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0230 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0231 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0232 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0233 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0234 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0235 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0236 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0237 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0238 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0239 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0240 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0241 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0242 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0243 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0244 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0245 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0246 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0247 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0248 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0249 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0250 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0251 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0252 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0253 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0254 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0255 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0256 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0257 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0258 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0259 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0260 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0261 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0262 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0263 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0264 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0265 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0266 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0267 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0268 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0269 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0270 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0271 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0272 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0273 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0274 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0275 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0276 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0277 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0278 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0279 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0280 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0281 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0282 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0283 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0284 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0285 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0286 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0287 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0288 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0289 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0290 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0291 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0292 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0293 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0294 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0295 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0296 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0297 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0298 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0299 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0300 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0301 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0302 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0303 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0304 - padding so probe throws land on exact, pre-recorded line numbers
@pragma('vm:never-inline')
void probeF() {
  throw StateError('SAURON_PROBE id=F line=307');
}
// filler 0309 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0310 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0311 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0312 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0313 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0314 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0315 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0316 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0317 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0318 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0319 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0320 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0321 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0322 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0323 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0324 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0325 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0326 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0327 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0328 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0329 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0330 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0331 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0332 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0333 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0334 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0335 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0336 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0337 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0338 - padding so probe throws land on exact, pre-recorded line numbers
void probeGInner() {
  throw StateError('SAURON_PROBE id=G line=340');
}
// filler 0342 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0343 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0344 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0345 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0346 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0347 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0348 - padding so probe throws land on exact, pre-recorded line numbers
// filler 0349 - padding so probe throws land on exact, pre-recorded line numbers
@pragma('vm:never-inline')
void probeHWrapper() {
  probeGInner(); // SAURON_PROBE id=H line=352 wrapper-calls-inlinable
}

final Map<String, void Function()> kProbes = <String, void Function()>{
  'A': probeA,
  'B': probeB,
  'C': probeC,
  'D': probeD,
  'E': probeE,
  'F': probeF,
  'H': probeHWrapper,
};
